### ISSUE TITLE
fib.c doesn't finish

### ISSUE THREAD

**Issue by ankoman** [virtualsecureplatform/kvsp#8]
Hi all,

I built kvsp on almost clean Ubuntu 20.04 (WSL2) without GPU, and tried to run the fib.c example.

I executed fib.enc executable for 90 cycles in total, but decrypted result.enc shows that the execution doesn't finish as the following:

        $ ./kvsp dec -k secret.key -i result.enc
        [2021-05-12 20:59:36.636] [iyokan-packet] [info] Starting dec...
        [2021-05-12 20:59:37.218] [iyokan-packet] [info] dec done. (0 seconds)
        [2021-05-12 20:59:37.308] [iyokan-packet] [info] Starting packet2toml...
        [2021-05-12 20:59:37.314] [iyokan-packet] [info] packet2toml done. (0 seconds)
        #cycle  90
        
        f0      false
        
        x0      14
        x1      498
        x2      0
        x3      0
        x4      0
        x5      0
        x6      0
        x7      0
        x8      5
        x9      500
        x10     0
        x11     0
        x12     0
        x13     0
        x14     0
        x15     0
        
                 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
        000000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000030  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000040  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000050  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000060  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000070  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0000a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0000b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0000c0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0000d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0000e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0000f0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000100  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000110  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000120  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000130  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000140  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000150  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000160  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000170  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000180  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        000190  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0001a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0001b0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0001c0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0001d0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0001e0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
        0001f0  00 00 02 00 fb 01 fc 01 00 00 00 00 35 00 f2 01

Do you have any ideas of what causes this problem?

**Comment by ushitora-anqou** [comment]
Thanks for your feedback.

I couldn't reproduce your result, but you may have forgotten to pass a command-line argument to fib.c, that is, `5`:
```
$ ./kvsp enc -k secret.key -i fib -o fib.enc 5 # This five
```
If it is not true, please copy and paste here the commands of kvsp you entered. I may well be able to find other causes from them.

**Comment by ankoman** [comment]
I solved this problem.

I compiled fib.c in example folder, where the main function is:

        int main() {
          // The result will be set in the register x8.
          return fib(5);
        }.

Generated asm codes were highly optimized by the compiler. There was just two instructions:

	lsi	a0, 5
	jr	ra

I suspect termination decision doesn't work well in the case such as the short codes.

**Comment by ushitora-anqou** [comment]
Hmm. In my environment, both fib.c worked fine. Here are the commands I entered:

```sh
$ ./kvsp cc fib.c -o fib # This fib.c is the example/fib.c
$ ./kvsp genkey -o secret.key
$ ./kvsp genbkey -i secret.key -o bootstrapping.key
$ ./kvsp enc -k secret.key -i fib -o fib.enc
$ ./kvsp run -bkey bootstrapping.key -i fib.enc -o result.enc -c 16 # Actually example/fib.c takes only 16 cycles.
$ ./kvsp dec -k secret.key -i result.enc
```

Could you try this out also in your environment?

**Comment by ushitora-anqou** [comment]
I noticed that `-c 16` shows `f0 true`, but `-c 30` shows `f0 false`. This is probably a bug of KVSP.

**Comment by ushitora-anqou** [comment]
This bug was caused by our processor cahp-ruby. We fixed the bug in the [commit acc1df8](https://github.com/virtualsecureplatform/cahp-ruby/commit/acc1df802d228abfc6c8378ca7a4dbd607daa1d9) of cahp-ruby and the [commit a228cb9](https://github.com/virtualsecureplatform/kvsp/commit/a228cb9aef7029cbb57ce2d697e871cf686ef593) of kvsp. We also released KVSP [v31](https://github.com/virtualsecureplatform/kvsp/releases/tag/v31) including this fix.

Thanks a lot for your contribution!

**Comment by ankoman** [comment]
Thank you for fixing.
I want you to rewrite README, too.
It says
> f0 is 'finish flag', which is true iff the program ends. So, 30 cycles were not enough. Let's try another 30; 
It looks wrong.

Thank you.

**Comment by ushitora-anqou** [comment]
I don't think it's wrong, since fib.c in README takes more than 30 cycles. But it is surely confusing that fib.c in README is different from example/fib.c. We will resolve this soon.
